### ISSUE TITLE
How to download and use

### ISSUE THREAD

**Issue by reidq7** [LegendOfMCPE/SlapIt#2]
So I transferred all files to my server and made a phar file with DevTools, but I don't see any commands or plugins. However it is recognized as a plugin. Do you know how to use this?

**Comment by PEMapModder** [comment]
This plugin is not ready. Currently it is under API design stage, and it has no commands yet.

**Comment by DinoKill** [comment]
I like trains

**Comment by PEMapModder** [comment]
@DinoKill what?

**Comment by DinoKill** [comment]
just thought i would share it here

**Comment by reidq7** [comment]
How much progress would you estimate you're done with? Maybe you know a percentage or something?

**Comment by PEMapModder** [comment]
Well you can consider it as nothing done, since we are just designing the data saving and event firing part.
